<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Authors>CloudHolic</Authors>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Strings.fs" />
		<Compile Include="Error.fs" />
		<Compile Include="Model.fs" />
		<Compile Include="Parser\State.fs" />
		<Compile Include="Parser\Lex.fs" />
		<Compile Include="Parser\Fields.fs" />
		<Compile Include="Parser\Checks.fs" />
		<Compile Include="Parser\Assembly.fs" />
		<Compile Include="Parser\Scan.fs" />
		<Compile Include="Writer.fs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FParsec" Version="1.1.1" />
		<PackageReference Include="FsToolkit.ErrorHandling" Version="5.2.0" />
	</ItemGroup>

</Project>
