[project]
name = "urc-converter"
version = "0.1.0"
description = "URC (Universal Rhythm Chart) parser and converter library"
requires-python = ">=3.14"
license = "MIT"
authors = [
    { name = "CloudHolic", email = "cloudholic@pm.me" }
]
dependencies = [
    "pyyaml>=6.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
	"ruff"
]

[tool.hatch.build.targets.wheel]
packages = ["src/urc_converter"]

[tool.ruff]
line-length = 100
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "N"]

[tool.ruff.format]
indent-style = "tab"
quote-style = "double"
